import base64
import json
import os
import secrets
import socket
import sys
import tempfile
import time
import urllib.request
import zipfile
from datetime import datetime, timezone
from pathlib import Path


EXIT_OPERATIONAL_ERROR = 2


def local_environment_values() -> dict[str, str]:
    return {
        "AEGIS_ENV": "development",
        "AEGIS_DOMAIN": "http://localhost",
        "AEGIS_ALLOWED_HOSTS": "localhost,127.0.0.1",
        "AEGIS_CORS_ORIGINS": "http://localhost",
        "AEGIS_REQUIRE_AUTH": "true",
        "AEGIS_ADMIN_TOKEN": secrets.token_urlsafe(40),
        "AEGIS_SESSION_SECRET": secrets.token_urlsafe(48),
        "AEGIS_BOOTSTRAP_ADMIN_USERNAME": "admin",
        "AEGIS_BOOTSTRAP_ADMIN_PASSWORD": secrets.token_urlsafe(24),
        "AEGIS_METRICS_TOKEN": secrets.token_urlsafe(40),
        "AEGIS_SETUP_TOKEN": secrets.token_urlsafe(48),
        "AEGIS_ENCRYPTION_KEY": base64.urlsafe_b64encode(secrets.token_bytes(32)).decode(),
        "POSTGRES_PASSWORD": secrets.token_urlsafe(32),
        "AEGIS_SKIP_EXTERNAL_SCANNERS": "false",
    }


def read_environment_file(path: Path) -> dict[str, str]:
    values = {}
    if not path.exists():
        return values
    for line in path.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        values[key] = value
    return values


def write_environment_file(path: Path, values: dict[str, str]) -> None:
    lines = [
        "# Generated by `aegis start`. Keep this file private.",
        *(f"{key}={value}" for key, value in values.items()),
        "",
    ]
    path.write_text("\n".join(lines))
    os.chmod(path, 0o600)


def docker_compose_command(project_root: Path, env_file: Path, *arguments: str) -> list[str]:
    return [
        "docker",
        "compose",
        "--project-directory",
        str(project_root),
        "--env-file",
        str(env_file),
        *arguments,
    ]


def port_is_available(port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as probe:
        probe.settimeout(0.2)
        return probe.connect_ex(("127.0.0.1", port)) != 0


def wait_for_dashboard(url: str, timeout: int = 180) -> bool:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            with urllib.request.urlopen(f"{url}/health", timeout=3) as response:
                if response.status == 200:
                    return True
        except Exception:
            time.sleep(2)
    return False


def run_start(
    *,
    project_root: Path,
    local_env_file: Path,
    subprocess_module,
    shutil_module,
    webbrowser_module,
    no_open: bool = False,
    foreground: bool = False,
    regenerate_secrets: bool = False,
    is_port_available=port_is_available,
    wait_for_ready=wait_for_dashboard,
) -> int:
    compose_file = project_root / "docker-compose.yml"
    if not compose_file.exists():
        print("Aegis start requires a source checkout containing docker-compose.yml.", file=sys.stderr)
        return EXIT_OPERATIONAL_ERROR
    if shutil_module.which("docker") is None:
        print("Docker is required. Install Docker Desktop or Docker Engine, then rerun `aegis start`.", file=sys.stderr)
        return EXIT_OPERATIONAL_ERROR
    version = subprocess_module.run(
        ["docker", "compose", "version"],
        capture_output=True,
        text=True,
        check=False,
    )
    if version.returncode != 0:
        print("Docker Compose v2 is required (`docker compose`).", file=sys.stderr)
        return EXIT_OPERATIONAL_ERROR

    if regenerate_secrets or not local_env_file.exists():
        previous = read_environment_file(local_env_file)
        generated = local_environment_values()
        if previous.get("POSTGRES_PASSWORD"):
            generated["POSTGRES_PASSWORD"] = previous["POSTGRES_PASSWORD"]
        write_environment_file(local_env_file, generated)
        print(f"Created private local configuration: {local_env_file}")
    values = read_environment_file(local_env_file)
    required = {
        "AEGIS_SETUP_TOKEN",
        "POSTGRES_PASSWORD",
        "AEGIS_SESSION_SECRET",
        "AEGIS_ENCRYPTION_KEY",
    }
    if not required.issubset(values):
        print(
            f"{local_env_file} is incomplete. Use `aegis start --regenerate-secrets` to replace it.",
            file=sys.stderr,
        )
        return EXIT_OPERATIONAL_ERROR

    running = subprocess_module.run(
        docker_compose_command(project_root, local_env_file, "ps", "--status", "running", "--quiet"),
        capture_output=True,
        text=True,
        check=False,
    )
    if not running.stdout.strip():
        occupied = [str(port) for port in (80, 443) if not is_port_available(port)]
        if occupied:
            print(
                "Cannot start Aegis because these ports are already in use: "
                + ", ".join(occupied),
                file=sys.stderr,
            )
            return EXIT_OPERATIONAL_ERROR

    command = docker_compose_command(project_root, local_env_file, "up", "--build")
    if not foreground:
        command.append("-d")
    print("Starting PostgreSQL, Redis, worker, dashboard, and reverse proxy...")
    result = subprocess_module.run(command, cwd=project_root, check=False)
    if result.returncode != 0:
        return result.returncode
    if foreground:
        return 0

    base_url = "http://localhost"
    print("Waiting for Aegis to become healthy...")
    if not wait_for_ready(base_url):
        print(
            "Aegis did not become healthy within 180 seconds. Run `docker compose logs` for details.",
            file=sys.stderr,
        )
        return EXIT_OPERATIONAL_ERROR

    setup_url = f"{base_url}/setup#{values['AEGIS_SETUP_TOKEN']}"
    print(f"Aegis is ready: {base_url}")
    print(f"First-run setup: {setup_url}")
    print("Configuration is stored in .env.aegis with owner-only permissions.")
    if not no_open:
        try:
            webbrowser_module.open(setup_url)
        except Exception:
            pass
    return 0


def require_local_stack(*, local_env_file: Path, shutil_module) -> bool:
    if not local_env_file.exists():
        print("No local stack configuration found. Run `aegis start` first.", file=sys.stderr)
        return False
    if shutil_module.which("docker") is None:
        print("Docker is required for this command.", file=sys.stderr)
        return False
    return True


def run_stop(*, project_root: Path, local_env_file: Path, subprocess_module, shutil_module) -> int:
    if not require_local_stack(local_env_file=local_env_file, shutil_module=shutil_module):
        return EXIT_OPERATIONAL_ERROR
    return subprocess_module.run(
        docker_compose_command(project_root, local_env_file, "down"),
        cwd=project_root,
        check=False,
    ).returncode


def run_stack_logs(*, project_root: Path, local_env_file: Path, subprocess_module, shutil_module, follow: bool = False) -> int:
    if not require_local_stack(local_env_file=local_env_file, shutil_module=shutil_module):
        return EXIT_OPERATIONAL_ERROR
    command = docker_compose_command(project_root, local_env_file, "logs", "--tail", "200")
    if follow:
        command.append("--follow")
    return subprocess_module.run(command, cwd=project_root, check=False).returncode


def run_upgrade(
    *,
    project_root: Path,
    local_env_file: Path,
    subprocess_module,
    shutil_module,
    webbrowser_module,
    run_start_callback,
    no_start: bool = False,
) -> int:
    git_directory = project_root / ".git"
    if git_directory.exists():
        dirty = subprocess_module.run(
            ["git", "status", "--porcelain"],
            cwd=project_root,
            capture_output=True,
            text=True,
            check=False,
        )
        if dirty.stdout.strip():
            print("Upgrade stopped because the source checkout has uncommitted changes.", file=sys.stderr)
            return EXIT_OPERATIONAL_ERROR
        result = subprocess_module.run(["git", "pull", "--ff-only"], cwd=project_root, check=False)
    else:
        result = subprocess_module.run(
            [sys.executable, "-m", "pip", "install", "--upgrade", "aegis-security-console"],
            check=False,
        )
    if result.returncode != 0 or no_start:
        return result.returncode
    return run_start_callback(no_open=True)


def run_backup(
    *,
    project_root: Path,
    local_env_file: Path,
    subprocess_module,
    shutil_module,
    package_version: str,
    output: str | None = None,
) -> int:
    if not require_local_stack(local_env_file=local_env_file, shutil_module=shutil_module):
        return EXIT_OPERATIONAL_ERROR
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    destination = Path(output or f"aegis-backup-{timestamp}.zip").expanduser().resolve()
    with tempfile.TemporaryDirectory(prefix="aegis-backup-") as temporary:
        root = Path(temporary)
        dump = subprocess_module.run(
            docker_compose_command(
                project_root,
                local_env_file,
                "exec",
                "-T",
                "postgres",
                "pg_dump",
                "--clean",
                "--if-exists",
                "-U",
                "aegis",
                "-d",
                "aegis",
            ),
            cwd=project_root,
            capture_output=True,
            check=False,
        )
        if dump.returncode != 0:
            print("PostgreSQL backup failed.", file=sys.stderr)
            return EXIT_OPERATIONAL_ERROR
        (root / "database.sql").write_bytes(dump.stdout)
        copy = subprocess_module.run(
            docker_compose_command(project_root, local_env_file, "cp", "dashboard:/data/scans", str(root / "scans")),
            cwd=project_root,
            check=False,
        )
        if copy.returncode != 0:
            print("Report backup failed.", file=sys.stderr)
            return EXIT_OPERATIONAL_ERROR
        (root / "manifest.json").write_text(
            json.dumps({"created_at": datetime.now(timezone.utc).isoformat(), "version": package_version}, indent=2)
        )
        destination.parent.mkdir(parents=True, exist_ok=True)
        with zipfile.ZipFile(destination, "w", zipfile.ZIP_DEFLATED) as archive:
            for path in root.rglob("*"):
                if path.is_file():
                    archive.write(path, path.relative_to(root))
    print(f"Backup created: {destination}")
    return 0


def run_restore(
    archive_path: str,
    *,
    project_root: Path,
    local_env_file: Path,
    subprocess_module,
    shutil_module,
    confirmed: bool = False,
) -> int:
    if not confirmed:
        print("Restore replaces database and report state. Rerun with --yes.", file=sys.stderr)
        return EXIT_OPERATIONAL_ERROR
    if not require_local_stack(local_env_file=local_env_file, shutil_module=shutil_module):
        return EXIT_OPERATIONAL_ERROR
    archive = Path(archive_path).expanduser().resolve()
    if not archive.exists():
        print(f"Backup does not exist: {archive}", file=sys.stderr)
        return EXIT_OPERATIONAL_ERROR
    with tempfile.TemporaryDirectory(prefix="aegis-restore-") as temporary:
        root = Path(temporary)
        with zipfile.ZipFile(archive) as source:
            if "database.sql" not in source.namelist():
                print("Invalid Aegis backup: database.sql is missing.", file=sys.stderr)
                return EXIT_OPERATIONAL_ERROR
            for member in source.namelist():
                target = (root / member).resolve()
                if not target.is_relative_to(root.resolve()):
                    print("Invalid Aegis backup: unsafe archive path.", file=sys.stderr)
                    return EXIT_OPERATIONAL_ERROR
            source.extractall(root)
        subprocess_module.run(
            docker_compose_command(project_root, local_env_file, "stop", "dashboard", "worker"),
            cwd=project_root,
            check=False,
        )
        restore = subprocess_module.run(
            docker_compose_command(project_root, local_env_file, "exec", "-T", "postgres", "psql", "-U", "aegis", "-d", "aegis"),
            cwd=project_root,
            input=(root / "database.sql").read_bytes(),
            check=False,
        )
        if restore.returncode != 0:
            print("Database restore failed.", file=sys.stderr)
            return EXIT_OPERATIONAL_ERROR
        scans = root / "scans"
        if scans.exists():
            subprocess_module.run(
                docker_compose_command(project_root, local_env_file, "cp", str(scans), "dashboard:/data/"),
                cwd=project_root,
                check=False,
            )
        return subprocess_module.run(
            docker_compose_command(project_root, local_env_file, "up", "-d", "dashboard", "worker"),
            cwd=project_root,
            check=False,
        ).returncode
